### ISSUE TITLE
Change IAA Logo

### ISSUE THREAD

**Issue by OritandJoe** [Scripta-Qumranica-Electronica/ScrollEditor#100]
Please Change IAA Logo to the new logo
![reshotHaatikot_logo_black copy](https://user-images.githubusercontent.com/83159010/115986092-59419300-a5b7-11eb-9645-85d0b7d8309f.png)

**Comment by Bronson-Brown-deVost** [comment]
@zmbq @Bronson-Brown-deVost when going to fix this, please check with all other partners that we have the proper institutional image.  Also agree on layout (check with PIs).
