### ISSUE TITLE
Landing page broken links

### ISSUE THREAD

**Issue by OritandJoe** [Scripta-Qumranica-Electronica/ScrollEditor#101]
1. all three links at the bottom of the landing page do not work
2. "Dead Sea Scrolls Website" should be "The Leon Levy Dead Sea Scrolls Digital Library", and only needs to appear once
3. Institution logos should be links to their websites

**Comment by Bronson-Brown-deVost** [comment]
@zmbq do you have the necessary links already?

**Comment by tsviar** [comment]
Fixed in branch fix/GIT-issues-rest
![image](https://user-images.githubusercontent.com/16132723/119405170-85048580-bce9-11eb-8b5d-d7e27f497f12.png)
