### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by OritandJoe** [Scripta-Qumranica-Electronica/ScrollEditor#102]
1. Search should only appear once you enter the Scrollery
2. Search currently does not seem to work

**Comment by Bronson-Brown-deVost** [comment]
1. Agreed, @zmbq @tsviar this should be pretty easy right?
2. It is working now.

**Comment by tsviar** [comment]
Item 1 solved in branch fix/GIT-issues-rest
![image](https://user-images.githubusercontent.com/16132723/120495431-5fe8d480-c3c5-11eb-8274-667ba44f453e.png)
![image](https://user-images.githubusercontent.com/16132723/120495501-7000b400-c3c5-11eb-92d7-5a410a779f16.png)
