### ISSUE TITLE
Text on Editions Page

### ISSUE THREAD

**Issue by OritandJoe** [Scripta-Qumranica-Electronica/ScrollEditor#104]
1. "My editions are editions you are currently working on or have previously published" - should be "Editions you are currently working on or have previously published"
2. Public editions should have a similar caption: "Editions published in the scrollery"

**Comment by Bronson-Brown-deVost** [comment]
This is ok, though I think we were going to change the terminology from "personal editions" into "workspaces".

**Comment by tsviar** [comment]
Fixed in branch "fix/GIT-issues-rest
