### ISSUE TITLE
Invitation to edit 

### ISSUE THREAD

**Issue by oritRosengarten** [Scripta-Qumranica-Electronica/ScrollEditor#110]
the e-mail needs to be fixed, it is missing the word "days" at the end of the sentence 
(which is now "Joe Uziel has invited you to become an editor on 11Q13 malkisedeq. To accept the invitation, please click here. If you do not wish to accept this invitation, no action is necessary on your part and the invitation will expire in 10".)

Also, when I except the invitation it does not give me an opportunity to accept without signing and does not allow me to sign in (I attached a screen shot)
![bug 5](https://user-images.githubusercontent.com/74494426/116036962-1e4f6600-a670-11eb-9c97-8c691c78f0d3.JPG)

**Comment by Bronson-Brown-deVost** [comment]
The email message is fixed and will be updated on the production instance shortly.

@zmbq can you address the VRE issue regarding inability to login?
