### ISSUE TITLE
Editions Page

### ISSUE THREAD

**Issue by OritandJoe** [Scripta-Qumranica-Electronica/ScrollEditor#111]
1. Tiles should be highlighted when hovered over
2. In Personal Editions, tile should have watermark with "Edit" or edit icon when mouse is on the tile, to notify the user that by clicking the icon, he will enter the edit mode
3. In Public Editions, tile should have clear instructions for two options: View or Create a Copy, when hovering over tile

**Comment by Bronson-Brown-deVost** [comment]
I'm not so sure about these requests.  Can we ask the group about them before moving to implementation?

**Comment by OritandJoe** [comment]
Sounds good

**Comment by zmbq** [comment]
Other than highlighting on hover, the others have been handled (in a consistent and simple way). I don't like things highlighted on hover too much, so I'd rather not do that.
