### ISSUE TITLE
toolbars in Artifact View

### ISSUE THREAD

**Issue by OritandJoe** [Scripta-Qumranica-Electronica/ScrollEditor#118]
1. controls (+/-, left/right rotate) are spaced unevenly from textbox - should be together
2. tooltip only appears for rotate - zoom should have tooltip or magnifying glass icon with +/-

**Comment by Bronson-Brown-deVost** [comment]
Yes, there still needs to be some cleanup here. @zmbq how hard is it to handle the smaller screen size from a layout perspective?  See images below:

![Screen Shot 2021-05-06 at 10 30 42](https://user-images.githubusercontent.com/2952608/117267013-1d7bb880-ae56-11eb-9b07-105df2008b3e.png)
![Screen Shot 2021-05-06 at 10 31 27](https://user-images.githubusercontent.com/2952608/117267105-38e6c380-ae56-11eb-9564-7b5088978dcf.png)

**Comment by Bronson-Brown-deVost** [comment]
I think point 3 in #121 would also have an influence here, since making the text box wider would affect the toolbar sizes in the current HTML layout.
