### ISSUE TITLE
Artefact editor Text Window

### ISSUE THREAD

**Issue by OritandJoe** [Scripta-Qumranica-Electronica/ScrollEditor#121]
1. Pull down menu does not allow you to change the text for the fragment once you have chosen one
2. Switch up/down buttons do not work
3. Enable resizing the text area
4. Allow text font enlargement

**Comment by Bronson-Brown-deVost** [comment]
1. @zmbq , when you select a text fragment in the artefact editor, it leaves the text of that fragment's name in the filter box of the select drop-down.  This makes it look like you cannot select another text fragment, but you actually can if you delete the current fragment name.  Maybe we delete the filter text in the drop down select after a text has been chosen?
2. The "switch up" and "switch down" buttons do not do what people expect it to do.  Two suggestions: only show these buttons if you have more than one text fragment in view (they are really meaningless with a single text fragment); change the text to "move up"/"move down".  Related to this, it is not necessarily intuitive that clicking on the name of the fragment makes it show/hide.  Maybe add a dedicated icon instead? Perhaps an open/closed eye icon, or probably better the common show/collapse caret.
3. How hard would this be? I often find myself wanting it.
4. Should we offer dedicated text enlargement for this text view pane, or should we rely on the browser text zoom functionality.  I don't know which is better from an A11Y standpoint.

**Comment by Bronson-Brown-deVost** [comment]
For point 2, perhaps like this:

![Fragment-display](https://user-images.githubusercontent.com/2952608/117265141-37b49700-ae54-11eb-82c6-212427e2f817.png)

**Comment by OritandJoe** [comment]
4. We think text enlargement should be for the text pane only, not dependent on the browser zoom, especially since the image has its own zoom

**Comment by tsviar** [comment]
1 and 2 now work in fix/GIT-issues-rest.
up and down buttons do work, here are some snapshots (4Q51)
![image](https://user-images.githubusercontent.com/16132723/118687324-8aeff780-b80d-11eb-99c8-5eb91ddee687.png)

Arrow down
![image](https://user-images.githubusercontent.com/16132723/118687378-9ba06d80-b80d-11eb-88ee-4b3bd7b8283c.png)
![image](https://user-images.githubusercontent.com/16132723/118687389-9fcc8b00-b80d-11eb-88aa-575ec5e101ef.png)

Arrow up on the 2nd 
![image](https://user-images.githubusercontent.com/16132723/118687436-ae1aa700-b80d-11eb-89a8-02d0bc6f82dc.png)
![image](https://user-images.githubusercontent.com/16132723/118687450-b1159780-b80d-11eb-9231-8897fb74b650.png)

**Comment by zmbq** [comment]
All the text editing is going to be different soon, handled in another issue. Closing this.
