### ISSUE TITLE
Add "delete edition" button

### ISSUE THREAD

**Issue by Bronson-Brown-deVost** [Scripta-Qumranica-Electronica/ScrollEditor#125]
Probably just add this to the card on the main personal editions module.

API support is DELETE /v1/editions/{editionId}

The API "Archives an edition so that it no longer appears in user data and searches. An admin
 may use the archiveForAllEditors optional parameter in order to archive the edition
 for all editors (must be confirmed with an archive token)."  The archive token is sent back with the first HTTP request to archiveForAllEditors.  Add that token to the query string to confirm the archive action.  

This delete can be undone easily by a system administrator by changing the "archived" flag in the "edition" table from 1 back to 0 for the desired edition ID.  Given a little more time, we could make it easily possible via the API to view all archived (deleted) editions, and also to restore an archived edition.  UI support would need to be added to that for users of the VRE.

**Comment by zmbq** [comment]
We will add a Delete Edition to the toolbar of private editions. Clicking the Delete button will open a modal saying "Are you sure you want to delete edition <edition name>?". Below it will be a text box with the message "type 'delete' to delete the edition". If people type 'delete', the DELETE button  of the modal will be enabled.

If they click it, the edition will be published. Shaindel, you will need to add a Service method that calls the API Bronson mentioned.

**Comment by shaindelb** [comment]
I did what needed to be done, but this returns to the 400 written error:

msg: "The request is not allowed because it violates the rule: an edition must have at least one admin.\nPlease give admin status to another editor before relinquishing admin status for the current user or deleting the edition.\nAn admin may delete the edition for all editors with the request DELETE /v1/editions/1647.."

Even though my status is defined as admin

**Comment by Bronson-Brown-deVost** [comment]
That sounds strange. I will look into it also. If I remember correctly it is a two step delete (archive) process. First an admin makes a request for delete that returns a token, then you make the delete request including that token. Does that sound like what you did?  I am checking the code right now.

**Comment by Bronson-Brown-deVost** [comment]
Ok, I know what is going on now. Any user can call DELETE /v1/editions/xxxx which will make that edition invisible to the user who requested the delete. It will still be visible to anyone with whom the edition had been shared. But, if the edition only has one admin and that admin tries to delete the edition this way it will fail because we really want to make certain (from the API) that the delete request was intentional. So the last admin of an edition must perform the delete as follows:

First make a request: DELETE /v1/editions/1647?optional=archiveForAllEditors which will return to you a token, then you must submit a request DELETE /v1/editions/1647?optional=archiveForAllEditors&token=the-token-you-just-received .  This will complete the deletion for you.

So, on the frontend when you perform the delete, you can have several cases to manage (with some user interaction):
1. If you are not an admin for the edition, DELETE /v1/editions/xxxx is all you need, it will just work. 
2. If you are an admin and there are no other editors of the edition, then do DELETE /v1/editions/1647?optional=archiveForAllEditors and then DELETE /v1/editions/1647?optional=archiveForAllEditors&token=the-token-you-just-received
3. If you are the only admin, but there are other editors, you should ask the user if s/he wishes to transfer admin rights to another editor or to delete the edition for everyone. 
    - For the first case, use the API to promote one of the other editors to admin, then demote yourself from admin (maybe to write access), then DELETE /v1/editions/xxxx will work.
    - For the second case do exactly the same as step 2 (above)

So I guess you will need some front end logic to help decide which of these cases applies and what user interaction (if any) is required.

**Comment by Bronson-Brown-deVost** [comment]
I think the above comment should now cover all the use cases.

**Comment by zmbq** [comment]
I think 3 is over complicated. If you are the only admin, and you delete, you delete for everyone and that's it. The UI should warn you that this is going to happen. If you don't want this to happen, manage the edition shares as you usually do, from the sharing popup.

**Comment by Bronson-Brown-deVost** [comment]
That sounds good to me, what you mention as a warning sounds perfectly fine. The admin will either delete for everyone or will know that s/he can to transfer ownership by naming another admin, then they can delete as per number 4.
