### ISSUE TITLE
Adding artefacts to editions

### ISSUE THREAD

**Issue by OritandJoe** [Scripta-Qumranica-Electronica/ScrollEditor#127]
There does not seem to be any option for allowing a scholar to add fragment from a different manuscript or edition. For example, If I decide that Frag. 1 of 4Q164 actually belongs to 4Q415, I cannot add it. It should appear in both the manuscript screen (add Artefact can have an option to add from other manuscripts) as well as in the main page of the edition where the tiles appear.

**Comment by zmbq** [comment]
We have added the ability to add imaged objects to editions, from there - artefacts are already supported.
