### ISSUE TITLE
Fix navbar

### ISSUE THREAD

**Issue by zmbq** [Scripta-Qumranica-Electronica/ScrollEditor#145]
1. Change "Search" into a magnifying glass icon.
2. Instead of user name show a user icon (person of some sort) and show the username as the top line of the dropdown menu.
3. In case the screen is not wide enough, hide "scripta qumranica..." (keep the logo) and "no changes"

To the right of the logged in user menu, add a hamburger menu with the following options:

1. About (which will open a popup - keep ithe popup empty for now)
2. Undo
3. Redo

And remove Undo/Redo from the navbar.

**Comment by tsviar** [comment]
Fixed as much as possible in branch fix/GIT issues-rest
![image](https://user-images.githubusercontent.com/16132723/119893548-2be45e00-bf44-11eb-8a00-9b2a761260eb.png)
![image](https://user-images.githubusercontent.com/16132723/119893557-30a91200-bf44-11eb-8cf9-795b297e0fdb.png)
![image](https://user-images.githubusercontent.com/16132723/119893578-37378980-bf44-11eb-8261-b3785259cb38.png)
![image](https://user-images.githubusercontent.com/16132723/119893595-3ef72e00-bf44-11eb-930d-e47857f7165d.png)

**Comment by tsviar** [comment]
![image](https://user-images.githubusercontent.com/16132723/119893932-a8773c80-bf44-11eb-9e4c-4ae98dd0232d.png)
 
![image](https://user-images.githubusercontent.com/16132723/119893958-ae6d1d80-bf44-11eb-9c8e-9510b1ae6f6b.png) 
![image](https://user-images.githubusercontent.com/16132723/119893972-b3ca6800-bf44-11eb-9362-34c5ceea8e44.png) 
![image](https://user-images.githubusercontent.com/16132723/119893997-b9c04900-bf44-11eb-8b75-e37c51b8a56c.png)

**Comment by zmbq** [comment]
Is it possible to revert the colors of the icons? They look weird with the white background.

**Comment by tsviar** [comment]
Change Search, User and About icons in branch fix/GIT-issues-june-2021
![image](https://user-images.githubusercontent.com/16132723/121053864-77103380-c7c4-11eb-87a8-2e69eabfb254.png)
![image](https://user-images.githubusercontent.com/16132723/121053872-7a0b2400-c7c4-11eb-9a6a-39d67c33ef4f.png)
![image](https://user-images.githubusercontent.com/16132723/121053884-7d9eab00-c7c4-11eb-9367-a2834532191c.png)
![image](https://user-images.githubusercontent.com/16132723/121053895-80999b80-c7c4-11eb-8a92-2a6a5e210760.png)
![image](https://user-images.githubusercontent.com/16132723/121053909-83948c00-c7c4-11eb-92db-df0d82cbdf31.png)
