### ISSUE TITLE
Imaged object mode

### ISSUE THREAD

**Issue by oritRosengarten** [Scripta-Qumranica-Electronica/ScrollEditor#158]
We have had 2 issues in this mode:
1. While masking an image there is no option to undo, has it been removed on purpose?
2. Erase Function - we keep on getting an error message, makes it very difficult to complete, is there any way to improve it?

**Comment by zmbq** [comment]
Check whether this is still relevant

**Comment by zmbq** [comment]
Undo is there, probably fixed since the issue was first created.
Erasing also seems to work.

Everything was probably fixed when we fixed other issues.
