### ISSUE TITLE
Make "public editions" the default edition page if there are no personal editions

### ISSUE THREAD

**Issue by Bronson-Brown-deVost** [Scripta-Qumranica-Electronica/ScrollEditor#164]
Submitter: Jonathan Ben Dov
Make "public editions" the default page rather than "my private editions". It seems to me that most users will seek access to multiple scrolls more often. Since the move from page to page is slow, this could become annoying.

**Comment by zmbq** [comment]
Private editions should be the default view when there are private editions, otherwise people are going to be irritated. So - make public editions the default if there are no private editions.
