### ISSUE TITLE
a grid that appears on some images, below 25 zoom  

### ISSUE THREAD

**Issue by oritRosengarten** [Scripta-Qumranica-Electronica/ScrollEditor#214]
On most of the images and artifacts, below 25 zoom, a slight grid appears.
Sometimes it is more noticeable and sometimes very gentle (in color and IR), I attached some examples. 
I am not sure why it happens (maybe it has something to do with the process or making them a pyramidal tiff in the IIIF server?).
We should be aware it exists and perhaps fix it when we have the chance. 
![Capture-lines2](https://user-images.githubusercontent.com/74494426/128061296-483e8fcb-0f40-4b8e-ae40-ad7325d1773e.JPG)
![Capture-lines1](https://user-images.githubusercontent.com/74494426/128061303-de371561-93d7-4199-afb4-f29e5cabba53.JPG)
![Capture-lines3](https://user-images.githubusercontent.com/74494426/128061305-5159451c-719e-49c2-b0d8-941dc857f18f.JPG)

**Comment by zmbq** [comment]
I think I fixed this by retrying loading the low res image in case of an error, like we do with tiles.
