### ISSUE TITLE
Scroll Bar - Meta data

### ISSUE THREAD

**Issue by OritandJoe** [Scripta-Qumranica-Electronica/ScrollEditor#283]
NO scroll bar appears to scroll down on the meta data

**Comment by zmbq** [comment]
The metadata should be placed in a popup window.

Add it to the toolbars of the ARtefact Editor, Imaged Object Editor, Manuscript Editor as well.

**Comment by zmbq** [comment]
Create an Edition Toolbox just with the Edition Information button that shows the popup.
