### ISSUE TITLE
Search editions when shifting from personal to public and back

### ISSUE THREAD

**Issue by zmbq** [Scripta-Qumranica-Electronica/ScrollEditor#305]
The text in the search box is retained, but the search is not performed when the view is replaced. Make sure the search is performed.

**Comment by OritandJoe** [comment]
As of now, the search command does not transfer from private to public, although the text remains. If it is not possible to have the search work - then there is no reason to leave the text. Even when hitting enter, the search doesn't update until you delete the text and retype it. Changed to high priority

**Comment by shaindelb** [comment]
i fixed search to filter also when swtching between private and public.
