### ISSUE TITLE
Design of upper banner

### ISSUE THREAD

**Issue by OritandJoe** [Scripta-Qumranica-Electronica/ScrollEditor#317]
1. center the menu
2. add i (for manuscript information) instead of the button that appears below 
see attached photo
![image](https://user-images.githubusercontent.com/83159010/140881469-130b9d40-1bbf-41ee-8b08-13551956f94b.png)

**Comment by zmbq** [comment]
Do number 2 (the i icon) and remove the Manuscript Editor button. As for centering - try it out, only if it's not too problematic with various screen sizes.
