### ISSUE TITLE
Erase an edition 

### ISSUE THREAD

**Issue by oritRosengarten** [Scripta-Qumranica-Electronica/ScrollEditor#324]
Is this an option? 
A user should be given the opportunity to erase it or at least rename an edition

Also, add an x option in the window: 
![cretae a copy](https://user-images.githubusercontent.com/74494426/141734794-73aab9d7-c794-4f1c-b7fa-939771db3e43.JPG)

**Comment by zmbq** [comment]
Duplicate of other issues
