### ISSUE TITLE
Display of multiple columns

### ISSUE THREAD

**Issue by OritandJoe** [Scripta-Qumranica-Electronica/ScrollEditor#338]
Display of multiple columns not working (at least for some scrolls), e.g., 2Q22:

https://sqe.deadseascrolls.org.il/editions/1774/artefacts/24404

**Comment by zmbq** [comment]
This is a private edition, we can't see it - please add a screen shot.

@OritandJoe

**Comment by oritRosengarten** [comment]
You cant see it on a screen shot, When I choose another text it just replaces the former one instead of showing them one on top of the other
