### ISSUE TITLE
Various bugs and issues reported by alpha user (Drew Longacre)

### ISSUE THREAD

**Issue by oritRosengarten** [Scripta-Qumranica-Electronica/ScrollEditor#341]
Error Reports
•	Whenever I add an artifact to the canvas, the artifact successfully adds, but I get the report: “Request failed with status code: 403”
•	On the canvas, when I change the number of degrees I want to rotate the artifact by, I get the same error report: “Request failed with status code: 403”. But the rotation seems to be working fine.
•	When I try to load 4Q11 or 11Q5 from the list of manuscripts, I get a “loading” circle, but the file page never loads. This is true for “published,” “manuscript”, “artefacts,” and “Imaged objects”
•	When I created a draft of 5/6Hev1b, I added an artefact. Even though the artifact loaded correctly, I received a “Network error” report.
•	Under the imaged objects section, I used the erase feature to remove some rice paper from the edges. It erased just fine, but I got the report “Imaged Object save failed”
•	After cleaning up an imaged object, I tried to rename it. When I clicked “rename” I got the report “artefact rename failed.”
•	In “Imaged Object” I edited an image and clicked “create new artefact”. On both occasions I tried it, I got an endless loading circle. The system seems to have created blank artefacts with the names I gave them.
•	In “Imaged Object” and “artefact”, the “Adjust image” button does not seem to be functional.
•	Under 5/6Hev1b, there are a number of “N/A” fragments that don’t belong to the scroll.
•	The attributes and general comment areas overlap with the text and are difficult to see/use (see screenshot below)

**Comment by RidgeBatty** [comment]
Fixed infinite loading circle bug with 4Q11 and 11Q5.
More issues surfaced: probably some of the images should not be there (need to check if there is a stitched image which replaces the partial images)

**Comment by zmbq** [comment]
@shaindelb , try this out, see if the 403 error still appears.
