### ISSUE TITLE
Ruler in "Manuscript" mode

### ISSUE THREAD

**Issue by AsafGayer** [Scripta-Qumranica-Electronica/ScrollEditor#378]
The rulers in the manuscript screen are awsome. however, they begin (0 point) in the left side of the screen which is less practicle for Hebrew. 
Would it possible to switch the 0 point to the right side of the canvas?  
Thanks!

**Comment by zmbq** [comment]
@Bronson-Brown-deVost , @OritandJoe - what do you think?

If we switch the ruler, we should also change the X coordinate displayed on the right pane.

**Comment by zmbq** [comment]
After deliberations, we have decided this can be more confusing than helpful.
