### ISSUE TITLE
Router addresses with "/"

### ISSUE THREAD

**Issue by Bronson-Brown-deVost** [Scripta-Qumranica-Electronica/ScrollEditor#60]
There are some imaged object IDs that contain a "/", which needs to be encoded when put into the URL.  For example, the route "https://www.qumranica.org/Scrollery/editions/361/imaged-objects/IAA-520/526-1" should instead be "https://www.qumranica.org/Scrollery/editions/361/imaged-objects/IAA-520%2F526-1" with "%2F" for the "/" in "IAA-520/526-1".  I guess it would be good practice in any event to escape the strings with `encodeURIComponent` before inserting them into the router.

**Comment by tsviar** [comment]
Example: 4Q396:

vue.runtime.esm.js?2b0e:619 [Vue warn]: Error in mounted hook (Promise/async): "Error: Can't find imaged object IAA-520/526-3 belonging to artefact 7370"

found in

---> <ArtefactImage> at src/components/artefact/artefact-image.vue
       <RouterLink>
         <ArtefactCard> at src/views/edition/components/artefact-card.vue
           <EditionArtefacts> at src/views/edition/components/artefacts.vue
             <Edition> at src/views/edition/Edition.vue
               <App> at src/App.vue
                 <Root>
warn @ vue.runtime.esm.js?2b0e:619
logError @ vue.runtime.esm.js?2b0e:1884
globalHandleError @ vue.runtime.esm.js?2b0e:1879
handleError @ vue.runtime.esm.js?2b0e:1839
eval @ vue.runtime.esm.js?2b0e:1856
Promise.then (async)
invokeWithErrorHandling @ vue.runtime.esm.js?2b0e:1856
callHook @ vue.runtime.esm.js?2b0e:4219
insert @ vue.runtime.esm.js?2b0e:3139
invokeInsertHook @ vue.runtime.esm.js?2b0e:6346
patch @ vue.runtime.esm.js?2b0e:6565
Vue._update @ vue.runtime.esm.js?2b0e:3948
updateComponent @ vue.runtime.esm.js?2b0e:4066
get @ vue.runtime.esm.js?2b0e:4479
run @ vue.runtime.esm.js?2b0e:4554
flushSchedulerQueue @ vue.runtime.esm.js?2b0e:4310
eval @ vue.runtime.esm.js?2b0e:1980
flushCallbacks @ vue.runtime.esm.js?2b0e:1906
Promise.then (async)
timerFunc @ vue.runtime.esm.js?2b0e:1933
nextTick @ vue.runtime.esm.js?2b0e:1990
queueWatcher @ vue.runtime.esm.js?2b0e:4402
update @ vue.runtime.esm.js?2b0e:4544
notify @ vue.runtime.esm.js?2b0e:730
reactiveSetter @ vue.runtime.esm.js?2b0e:1055
proxySetter @ vue.runtime.esm.js?2b0e:4631
onObserved @ artefact-card.vue?1d4d:58
intersectionObserver.IntersectionObserver.root @ artefact-card.vue?1d4d:38
vue.runtime.esm.js?2b0e:1888 Error: Can't find imaged object IAA-520/526-3 belonging to artefact 7370
    at VueComponent._callee$ (artefact-data-mixin.ts?bf01:23)
    at tryCatch (runtime.js?96cf:62)
    at Generator.invoke [as _invoke] (runtime.js?96cf:296)
    at Generator.prototype.<computed> [as next] (runtime.js?96cf:114)
    at asyncGeneratorStep (asyncToGenerator.js?1da1:3)
    at _next (asyncToGenerator.js?1da1:25)
    at eval (asyncToGenerator.js?1da1:32)
    at new Promise (<anonymous>)
    at VueComponent.eval (asyncToGenerator.js?1da1:21)
    at VueComponent.asyncMounted (artefact-data-mixin.ts?bf01:9)
logError @ vue.runtime.esm.js?2b0e:1888
globalHandleError @ vue.runtime.esm.js?2b0e:1879
handleError @ vue.runtime.esm.js?2b0e:1839
eval @ vue.runtime.esm.js?2b0e:1856
Promise.then (async)
invokeWithErrorHandling @ vue.runtime.esm.js?2b0e:1856
callHook @ vue.runtime.esm.js?2b0e:4219
insert @ vue.runtime.esm.js?2b0e:3139
invokeInsertHook @ vue.runtime.esm.js?2b0e:6346
patch @ vue.runtime.esm.js?2b0e:6565
Vue._update @ vue.runtime.esm.js?2b0e:3948
updateComponent @ vue.runtime.esm.js?2b0e:4066
get @ vue.runtime.esm.js?2b0e:4479
run @ vue.runtime.esm.js?2b0e:4554
flushSchedulerQueue @ vue.runtime.esm.js?2b0e:4310
eval @ vue.runtime.esm.js?2b0e:1980
flushCallbacks @ vue.runtime.esm.js?2b0e:1906
Promise.then (async)
timerFunc @ vue.runtime.esm.js?2b0e:1933
nextTick @ vue.runtime.esm.js?2b0e:1990
queueWatcher @ vue.runtime.esm.js?2b0e:4402
update @ vue.runtime.esm.js?2b0e:4544
notify @ vue.runtime.esm.js?2b0e:730
reactiveSetter @ vue.runtime.esm.js?2b0e:1055
proxySetter @ vue.runtime.esm.js?2b0e:4631
onObserved @ artefact-card.vue?1d4d:58
intersectionObserver.IntersectionObserver.root @ artefact-card.vue?1d4d:38
state-service.ts?9cd9:243 Edition 1649 has no script data

**Comment by tsviar** [comment]
Fixed this bug using your suggestion encodeURIComponent( this.imagedObject?.id)  in 
src\views\edition\components\imaged-objects.vue file.
and now it works :+))
Branch fix/ Git-hi-priority-fixes
