### ISSUE TITLE
fragment view, controls take too much space, Anonymous User Submission

### ISSUE THREAD

**Issue by Bronson-Brown-deVost** [Scripta-Qumranica-Electronica/ScrollEditor#61]
Submitter: Jonathan Ben Dov
When viewing a fragment, too much of the screen space is taken by the various controls, while only little space is left for the actual fragment. When using a laptop it makes things difficult to examine the fragment.

**Comment by Bronson-Brown-deVost** [comment]
@Bronson-Brown-deVost @zmbq , check if this is still true in the current interface.

**Comment by Bronson-Brown-deVost** [comment]
There is quite a bit more space now.  Check back with Jonathan to see if it is sufficient.

I am unsure that we can make more space for it at this point, making the image control menu hide could be an option. I don't think we could get to that before launch though.

**Comment by zmbq** [comment]
Since this is the best we can do, I can close this now.
