### ISSUE TITLE
1Q7 ImageDTO type color multiple times warning

### ISSUE THREAD

**Issue by tsviar** [Scripta-Qumranica-Electronica/ScrollEditor#63]
After creating a personal copy of 1Q7, when viewing Artefacts tab or Imaged objects tab,
there are 14 Warnings 
ImageDTO type color multiple times 

could be connected to the fact that for this artefact,
in Imaged Object Tab-> Adjust image-> 
the displayed dropdown menu is filled with 8 identical menu items named "color"
![multiple color field](https://user-images.githubusercontent.com/16132723/104428266-f474a680-558c-11eb-9882-de82e0b081a5.png)

Warning full text:
===================
image.ts?049c:151 ImageDTO has type  color  multiple times {id: 43479, images: Array(8), masterIndex: 7}
ImageStack @ image.ts?049c:151
ImagedObject @ imaged-object.ts?8ec1:24
eval @ imaged-object.ts?afcd:25
_callee$ @ imaged-object.ts?afcd:25
tryCatch @ runtime.js?96cf:62
invoke @ runtime.js?96cf:296
prototype.<computed> @ runtime.js?96cf:114
asyncGeneratorStep @ asyncToGenerator.js?1da1:3
_next @ asyncToGenerator.js?1da1:25
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js?1da1:13
_next @ asyncToGenerator.js?1da1:25
eval @ asyncToGenerator.js?1da1:32
eval @ asyncToGenerator.js?1da1:21
getEditionImagedObjects @ imaged-object.ts:70
_callee13$ @ state-service.ts?9cd9:240
tryCatch @ runtime.js?96cf:62
invoke @ runtime.js?96cf:296
prototype.<computed> @ runtime.js?96cf:114
asyncGeneratorStep @ asyncToGenerator.js?1da1:3
_next @ asyncToGenerator.js?1da1:25
eval @ asyncToGenerator.js?1da1:32
eval @ asyncToGenerator.js?1da1:21
imagedObjectsInternal @ state-service.ts?9cd9:241
eval @ state-service.ts?9cd9:106
wrapInternal @ state-service.ts?9cd9:168
imagedObjects @ state-service.ts?9cd9:106
_callee10$ @ state-service.ts?9cd9:201
tryCatch @ runtime.js?96cf:62
invoke @ runtime.js?96cf:296
prototype.<computed> @ runtime.js?96cf:114
asyncGeneratorStep @ asyncToGenerator.js?1da1:3
_next @ asyncToGenerator.js?1da1:25
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js?1da1:13
_next @ asyncToGenerator.js?1da1:25
eval @ asyncToGenerator.js?1da1:32
eval @ asyncToGenerator.js?1da1:21
editionInternal @ state-service.ts?9cd9:213
eval @ state-service.ts?9cd9:90
wrapInternal @ state-service.ts?9cd9:168
_callee2$ @ state-service.ts?9cd9:90
tryCatch @ runtime.js?96cf:62
invoke @ runtime.js?96cf:296
prototype.<computed> @ runtime.js?96cf:114
asyncGeneratorStep @ asyncToGenerator.js?1da1:3
_next @ asyncToGenerator.js?1da1:25
eval @ asyncToGenerator.js?1da1:32
eval @ asyncToGenerator.js?1da1:21
edition @ state-service.ts:162
_callee$ @ Edition.vue?9c45:158
tryCatch @ runtime.js?96cf:62
invoke @ runtime.js?96cf:296
prototype.<computed> @ runtime.js?96cf:114
asyncGeneratorStep @ asyncToGenerator.js?1da1:3
_next @ asyncToGenerator.js?1da1:25
eval @ asyncToGenerator.js?1da1:32
eval @ asyncToGenerator.js?1da1:21
mounted @ Edition.vue?9c45:92
invokeWithErrorHandling @ vue.runtime.esm.js?2b0e:1854
callHook @ vue.runtime.esm.js?2b0e:4219
insert @ vue.runtime.esm.js?2b0e:3139
invokeInsertHook @ vue.runtime.esm.js?2b0e:6346
patch @ vue.runtime.esm.js?2b0e:6565
Vue._update @ vue.runtime.esm.js?2b0e:3948
updateComponent @ vue.runtime.esm.js?2b0e:4066
get @ vue.runtime.esm.js?2b0e:4479
run @ vue.runtime.esm.js?2b0e:4554
flushSchedulerQueue @ vue.runtime.esm.js?2b0e:4310
eval @ vue.runtime.esm.js?2b0e:1980
flushCallbacks @ vue.runtime.esm.js?2b0e:1906
Promise.then (async)
timerFunc @ vue.runtime.esm.js?2b0e:1933
nextTick @ vue.runtime.esm.js?2b0e:1990
queueWatcher @ vue.runtime.esm.js?2b0e:4402
update @ vue.runtime.esm.js?2b0e:4544
notify @ vue.runtime.esm.js?2b0e:730
reactiveSetter @ vue.runtime.esm.js?2b0e:1055
eval @ vue-router.esm.js?8c4f:2932
eval @ vue-router.esm.js?8c4f:2931
updateRoute @ vue-router.esm.js?8c4f:2352
eval @ vue-router.esm.js?8c4f:2206
eval @ vue-router.esm.js?8c4f:2340
step @ vue-router.esm.js?8c4f:1944
step @ vue-router.esm.js?8c4f:1951
step @ vue-router.esm.js?8c4f:1951
runQueue @ vue-router.esm.js?8c4f:1955
eval @ vue-router.esm.js?8c4f:2335
step @ vue-router.esm.js?8c4f:1944
eval @ vue-router.esm.js?8c4f:1948
eval @ vue-router.esm.js?8c4f:2322
eval @ vue-router.esm.js?8c4f:2105
iterator @ vue-router.esm.js?8c4f:2300
step @ vue-router.esm.js?8c4f:1947
step @ vue-router.esm.js?8c4f:1951
step @ vue-router.esm.js?8c4f:1951
eval @ vue-router.esm.js?8c4f:1948
eval @ vue-router.esm.js?8c4f:2322
eval @ main.ts?cd49:89
iterator @ vue-router.esm.js?8c4f:2300
step @ vue-router.esm.js?8c4f:1947
step @ vue-router.esm.js?8c4f:1951
runQueue @ vue-router.esm.js?8c4f:1955
confirmTransition @ vue-router.esm.js?8c4f:2330
transitionTo @ vue-router.esm.js?8c4f:2203
push @ vue-router.esm.js?8c4f:2544
push @ vue-router.esm.js?8c4f:2966
handler @ vue-router.esm.js?8c4f:1133
invokeWithErrorHandling @ vue.runtime.esm.js?2b0e:1854
invoker @ vue.runtime.esm.js?2b0e:2179
original._wrapper @ vue.runtime.esm.js?2b0e:6917
Show 76 more frames

**Comment by Bronson-Brown-deVost** [comment]
I assume you will have this problem with any imaged object that has more than one artefact associated with it.  1Q7 has only one imaged object, but that object has 8 artefacts on it (which must be why you have 8 copies of the same image listed there).  You can look at the DTO you are getting back from the API request and decide if you think the DTO should be changed, or if you need to change the frontend code to filter out duplicates before displaying.  Let me know what you find out.

**Comment by tsviar** [comment]
It was fixed, does not appear anymore.
![image](https://user-images.githubusercontent.com/16132723/116565010-21678200-a90e-11eb-8fc6-0f1b163b902b.png)
