### ISSUE TITLE
1Q7 [Vue warn] Duplicate keys detected: 'color'

### ISSUE THREAD

**Issue by tsviar** [Scripta-Qumranica-Electronica/ScrollEditor#64]
Only in 1Q7, after creating a personal copy of 1Q7, 
when in Imaged Object Tab (or Artefact)
![Duplicte keys color 1Q7](https://user-images.githubusercontent.com/16132723/104429724-9d6fd100-558e-11eb-8da7-8bd07ad28376.png)
-> Adjust image-> 
the displayed dropdown menu is filled with 8 identical menu items named "color"
In 4Q51Copy this does not exist.

![multiple color field](https://user-images.githubusercontent.com/16132723/104428266-f474a680-558c-11eb-9882-de82e0b081a5.png)

Warning full text:
===================
![Duplicte keys color 1Q7](https://user-images.githubusercontent.com/16132723/104429221-0b67c880-558e-11eb-92a5-e954f80ab41a.png)

Relevant  code is:

\src\components\image-settings\ImageSettings.vue :

<template>
  <div>
      <single-image-setting v-for="imageType in imageStack.availableImageTypes" :key="imageType"
                :type="imageType" :settings="params.imageSettings[imageType]" @change=" onSingleImageSettingChanged($event)">
    </single-image-setting>
</div>
</template>

=> :key="imageType" not unique

**Comment by Bronson-Brown-deVost** [comment]
This will probably be fixed automatically when #63 gets fixed.

**Comment by tsviar** [comment]
It was fixed.
![image](https://user-images.githubusercontent.com/16132723/116565148-452ac800-a90e-11eb-8fed-5f2e977c05e3.png)
