### ISSUE TITLE
Fixed: navbar user operations dropdown menu was cutoff due to a shift to the right

### ISSUE THREAD

**Issue by tsviar** [Scripta-Qumranica-Electronica/ScrollEditor#68]
When clicking on user operations menu item, the dropdown  menu was displayed as cutoff due to a shift to the right.

Code fixed:
===============
src\components\navigation\Navbar.vue

added float: right option:

<b-nav-item-dropdown
                    v-if="userNameExists"
                    :text="userName"
                    id="register"
                     right   <= this was added
                >

![dropdown user menu](https://user-images.githubusercontent.com/16132723/104446394-0f521580-55a3-11eb-9302-f9ff9e7ee905.jpg)

**Comment by Bronson-Brown-deVost** [comment]
@tsviar @zmbq  it looks like this is fixed already. Can I close this issue?
