### ISSUE TITLE
Create Copy of wd36, XHev/Se32, and maybe others, problem

### ISSUE THREAD

**Issue by tsviar** [Scripta-Qumranica-Electronica/ScrollEditor#72]
Same as #67.
This problem occurs from the 2nd copy of any public artefact.
The routing to the artefact, after the "moda" is closed, fails to load all images, and only a refresh fixes it.

When creating copying wd36 and  XHev/Se32,
(http://localhost:8080/editions/1650/artefacts 
http://localhost:8080/editions/1652/artefacts )

this error was issued:

Utils.js?7ed1:201 [2021-01-17T15:55:04.951Z] Warning: No client method with the name 'CreatedEdition' found.
ConsoleLogger.log @ Utils.js?7ed1:201
HubConnection.invokeClientMethod @ HubConnection.js?98b8:635
HubConnection.processIncomingData @ HubConnection.js?98b8:512
HubConnection.connection.onreceive @ HubConnection.js?98b8:73
webSocket.onmessage @ WebSocketTransport.js?eb1a:112

src code:
==============
src\dtos\sqe-signalr.ts

    /**
	 * Add a listener for when the server broadcasts a new text edition has been created
	 *
	 */
    public connectCreatedEdition(handler: (msg: EditionDTO) => void): void {
        this._connection.on('**CreatedEdition'**, handler)
    }

    /**
	 * Remove an existing listener that triggers when the server broadcasts a new text edition has been created
	 *
	 */
    public disconnectCreatedEdition(handler: (msg: EditionDTO) => void): void {
        this._connection.off('**CreatedEdition**', handler)
    }

**Comment by Bronson-Brown-deVost** [comment]
Duplicate of #67?

**Comment by Bronson-Brown-deVost** [comment]
@zmbq @tsviar perhaps you can triage this and #67? I didn't look into it yet as the exact problem is not immediately obvious to me.

**Comment by tsviar** [comment]
same as #67, fixed in fix/GIT-hi-priority-fixes.
