### ISSUE TITLE
Allow adding an edition from the imaged object search result

### ISSUE THREAD

**Issue by zmbq** [Scripta-Qumranica-Electronica/ScrollEditor#73]
Add an "Attach Edition" button to the bottom of the imaged object search result. Button will pop up a dialog allowing you to select one of your personal editions. An Attach button will contact the endpoint that attaches an imaged object to an edition

**Comment by Bronson-Brown-deVost** [comment]
@zmbq , I guess we will need to decide whether we need a dedicated API endpoint for such operations (copy imaged object/artefact from edition to edition), or if you can just use the current API functionality (POST imaged object/POST artefact). I think tracking changes etc. might be more robust and simple if we use the current functionality (without any specialized "copy" endpoint), but it is probably not that big of a deal.

**Comment by zmbq** [comment]
We already have a way to add an imaged object to an edition.
