### ISSUE TITLE
ScriptData does not support MULTIPOLYGON of 2 signs in DTO.scripts 

### ISSUE THREAD

**Issue by tsviar** [Scripta-Qumranica-Electronica/ScrollEditor#83]
DTO.scripts i in \state\state-service.ts editionScriptInternal(editionId: number) containes 2 signes with a MULTIPOLYGON shape:

15:
character: "ץ"
creatorId: 2
editorId: 1646
scribalFontId: 1
shape: "MULTIPOLYGON(((13 15,8 15,3 17,3 19,4 19,5 23,10 22,13 21,13 15)),((129 1,128 0,126 0,120 9,120 13,116 18,106 23,106 24,96 28,91 36,92 40,89 41,89 46,91 56,94 59,107 58,111 56,117 51,121 50,123 47,128 49,132 46,145 46,153 41,156 34,160 25,160 20,154 10,148 5,136 2,129 1)),((7 59,7 64,10 64,10 66,12 69,11 69,16 70,16 71,19 71,15 65,15 63,20 59,20 52,14 47,10 41,10 36,12 36,12 30,6 24,4 24,2 25,0 37,3 42,3 48,5 50,5 59,7 59)),((76 114,75 114,71 116,72 138,75 153,78 165,78 172,75 176,78 189,80 193,83 193,86 189,90 181,92 162,89 145,88 133,89 126,88 122,76 114)))"
yOffset: -109
__proto__: Object

13:
character: "ף"
creatorId: 2
editorId: 1646
scribalFontId: 1
shape: "MULTIPOLYGON(((78 27,72 25,62 24,61 21,65 19,65 17,68 13,75 9,76 7,67 3,61 2,56 0,53 4,49 5,44 3,41 4,34 16,34 17,31 20,28 29,25 31,27 35,30 35,30 37,27 37,27 45,25 47,25 53,32 60,35 67,37 79,40 83,43 91,49 91,49 88,54 82,57 78,54 74,56 70,60 66,68 68,72 67,76 71,84 71,89 79,88 83,93 93,99 103,97 107,101 115,102 129,100 144,100 157,103 159,110 151,110 146,115 133,115 127,117 115,115 91,114 79,111 70,110 62,108 53,105 46,98 45,92 37,95 36,96 36,98 33,101 36,101 34,99 32,98 23,92 20,90 27,87 28,87 30,81 30,78 27),(36 32,37 34,35 34,35 32,36 32),(59 25,57 25,57 23,59 23,59 25),(66 32,63 33,60 31,62 29,66 31,66 32)),((7 107,10 111,11 112,20 112,24 114,24 110,26 106,22 101,21 90,21 74,17 64,14 61,8 61,4 65,4 67,2 70,0 72,0 84,8 98,6 102,7 107)))"
yOffset: -103
__proto__: Object

But GlyphData.shape in models\script.ts is of type Polygon and therefore it sets the svg as null
    public shape: Polygon;

ץ: GlyphData
character: "ץ"
shape: Polygon
_svg: ""
clipper: null
empty: true
geoJSON: null
svg: ""
wkt: ""
__proto__: Object
yOffset: -109
__proto__: Object

Resulting in these 2 signs not being displayed in scroll-area.

![MultiPolygon](https://user-images.githubusercontent.com/16132723/108354708-8017cd80-71f2-11eb-8a26-a5ab08afba32.jpg)
![MULTYPOLIGON2](https://user-images.githubusercontent.com/16132723/108355773-f23ce200-71f3-11eb-87f0-1f4d9897dbb0.jpg)

**Comment by Bronson-Brown-deVost** [comment]
@tsviar @zmbq I think I sent you the updated code to handle multipolygons already.  I think also that the fix has already been merged into the development branch. Can either of you confirm?

In any event, as a reminder to us all, the script shape may have a multipolygon because some characters are made up of non-continuous strokes, so multipoloygon is a valid shape type here.

**Comment by Bronson-Brown-deVost** [comment]
Yes, I see the fix has been applied.  Marking this closed.
