### ISSUE TITLE
Text attribute editing/commentary panel not visible

### ISSUE THREAD

**Issue by Bronson-Brown-deVost** [Scripta-Qumranica-Electronica/ScrollEditor#89]
I am on Chrome Version 90.0.4430.30 (Official Build) beta (x86_64) on a Mac. In the artefact editor, the panel for editing the text attributes and commentary gets pushed offscreen (see the image). Manually changing the height of the panel displaying the text transcription will make the panel become visible, so it is probably just a CSS alteration that needs to be made.
![Screen Shot 2021-03-22 at 12 50 48](https://user-images.githubusercontent.com/2952608/111986214-ef445280-8b0d-11eb-966b-70760d9b91dd.png)

**Comment by tsviar** [comment]
Artefact editor and it's text editor on the the right side was fixed in branch: "fix/GIT-issues-rest".
![image](https://user-images.githubusercontent.com/16132723/117656682-4f1bb900-b1a1-11eb-9ad3-a78d6770fd38.png)
