### ISSUE TITLE
Cannot clone personal editions

### ISSUE THREAD

**Issue by Bronson-Brown-deVost** [Scripta-Qumranica-Electronica/ScrollEditor#93]
When looking at the "Public Editions" each card offers the option to create a new personal edition from the public one.

We used to have this functionality also with the Private/Personal editions, but it seems now to be missing from the UI.  Probably add the possibility to clone directly from the edition cards in the Private/Personal edition view and perhaps also in the main page for the single edition (e.g., https://www.qumranica.org/Scrollery/editions/{editionId}/artefacts).

**Comment by tsviar** [comment]
Fixed in fix/GIT-hi-priority-fixes branch
Also fixed a bug of 2nd  copy operation did not properly display the artefact images, therefore added page refresh force.
